//alert("hola soy javascrip");
//console.log("saludos desde la consola");

/*document.getElementById("contenedor").innerHTML_`Js te envia un saludo`*/
/*var nombre="jennsi";*/
/*var edad=20;*/

/*alert("su nombre es;"+nombre + "su edades;"+ edad)
/*console.log("su nombre es: "+nombre + "su edad es:" + edad)*/
/*var nombre =prompt("escriba su nombre");*/
/*var edad =prompt("escriba su edad");*/

/*console.log("su nombre es:"+ nombre + "su edad es:"+ edad);*/




/*else {
    console.log("todavia eres menor de edad")

}*/



/*if(nombre==="jennsi"){
    console.log("tu no puedes entrar, no eres jennsi")
}*/


/*else{
    console.log("tu no eres jennsi")
}*/

/*function evaluarDatos(){

    var nombre= document.getElementById("nombre").value;
    var edad= document.getElementById("edad").value;

    console


}*/


